### ISSUE TITLE
Unable to import resources

### ISSUE THREAD

**Issue by ap-hyperbole** [opsgenie/opsgenie-cloudformation-resources#1]
When i run commands specified in the docs I keep gettin permissions error. 

AWS Command: 
------------
aws cloudformation register-type \
--region eu-west-1 \
--type-name "Atlassian::Opsgenie::User" \
--schema-handler-package "s3://opsgeniedownloads/cloudformation/atlassian-opsgenie-user.zip " \
--type RESOURCE

Error:
-------
An error occurred (CFNRegistryException) when calling the RegisterType operation: Error copying schemaHandlerPackage. Check the permissions on the bucket and object in your account and try again. 

Here is what I tried 

- Verified my role has permissions as it has admin access. 
- Tried executing this command on a different region but again got same error
- Uing latest version of AWS CLI i.e. aws-cli/1.16.294 Python/3.7.2 Darwin/18.7.0 botocore/1.13.30 
- Downloaded s3://opsgeniedownloads/cloudformation/atlassian-opsgenie-user.zip  file and uploaded to a bucket within our own account. Tried the command pointing at the bucket in our  own account. 

Any help would be appreciated.

**Comment by pgarbe** [comment]
Same here. Can you help @ffahri ?

**Comment by vladtsir** [comment]
You need to attach a policy to the S3 bucket where you put the schema/handler package to give `cloudformation.amazonaws.com` service principal access to the bucket and keys:

in case of "s3://opsgeniedownloads/cloudformation/atlassian-opsgenie-user.zip" and eu-west-1:

```
 ArtifactCopyPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: opsgeniedownloads
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: Allow CloudFormation to copy artifacts from the bucket
            Effect: Allow
            Principal:
              Service: cloudformation.amazonaws.com
            Action:
              - s3:ListBucket
              - s3:GetObject
            Resource:
              - !Sub "arn:aws:s3:::opsgeniedownloads"
              - !Sub "arn:aws:s3:::opsgeniedownloads/*"
```

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/registry.html
